FROM registry.access.redhat.com/ubi9/ubi:latest

# 1. Install required OS packages
# Added curl, tar, gzip for SDKMAN! (Dropped skopeo)
RUN dnf -y --noplugins --setopt=install_weak_deps=0 --setopt=tsflags=nodocs upgrade && \
    INSTALL_PKGS="jq wget unzip zip git glibc-langpack-en" && \
    dnf --disableplugin=subscription-manager -y --nodocs --setopt=install_weak_deps=0 install $INSTALL_PKGS && \
    dnf clean all && \
    rm -rf /var/cache/* /var/log/dnf* /var/log/yum.*

# 2. Install yq
RUN wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && \
    chmod a+x /usr/local/bin/yq

# 3. Setup Environment
WORKDIR /workdir
ENV HOME=/workdir \
    SBOMER_DOMINO_DIR="/workdir/domino" \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# 4. Set permissions for Tekton non-root user
RUN chown -R 65532:0 /workdir && \
    chmod -R g=u /workdir

USER 65532

# 5. Copy and run our generic install script
COPY --chown=65532:0 podman/java-agent/install.sh /workdir/

RUN bash ./install.sh && rm ./install.sh