apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.task.maven.configMapName }}
  labels:
    {{- include "java-generator-chart.labels" . | nindent 4 }}
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    {{- if .Values.task.maven.settingsContent }}
{{ .Values.task.maven.settingsContent | indent 6 }}
    {{- end }}
    </settings>